#!/usr/bin/env python3
"""
embedding_similarity_pass.py — detect cross-category nodes with high semantic similarity.

Reads brain-map/tree-data.json (generated by generate.py) and identifies pairs of
nodes from different categories that have high embedding-based semantic similarity
but lack a direct synapse edge between them.

Reasoning: nodes with similar semantic meaning but no explicit connection may
indicate conceptual overlap (e.g., two skills solving similar problems) that
should be surfaced for review.

Algorithm:
  1. Collect all nodes with non-empty descriptions (skip category-label trunks).
  2. Embed each description via the existing nomic-embed pipeline (Ollama).
  3. For each pair of embeddable nodes from different categories:
     - Compute cosine similarity.
     - If similarity >= THRESHOLD and no direct edge exists, emit a finding.
  4. Deduplicate by node pair (order-independent).
  5. Output findings for differentiation from sibling passes (#30 category-match,
     #31 shared-resource).

Output: brain-map/reports/embedding-similarity-gaps.json + .md rollup
"""
from __future__ import annotations

import argparse
import hashlib
import json
import math
import sys
from itertools import combinations
from pathlib import Path
from typing import TypedDict

HERE = Path(__file__).parent.parent
TREE_DATA_PATH = HERE / "tree-data.json"
OUTPUT_DIR = HERE / "reports"
OUTPUT_JSON = OUTPUT_DIR / "embedding-similarity-gaps.json"
OUTPUT_MD = OUTPUT_DIR / "embedding-similarity-gaps.md"

THRESHOLD = 0.8  # Conservative starting point; tunable via --threshold


class Finding(TypedDict):
    kind: str
    node_a: str
    node_b: str
    cat_a: str
    cat_b: str
    similarity: float
    reason: str


def collect_nodes(tree: dict) -> list[dict]:
    """Recursively collect all nodes with non-empty descriptions."""
    result = []

    def walk(node: dict) -> None:
        # Include node if it has a non-empty description
        if node.get("desc", "").strip():
            result.append(
                {
                    "id": node.get("id", ""),
                    "cat": node.get("cat", ""),
                    "desc": node.get("desc", ""),
                }
            )
        # Recurse into children
        for child in node.get("children", []):
            walk(child)

    walk(tree)
    return result


def _desc_hash(desc: str) -> str:
    """SHA256 hash of description for cache invalidation."""
    return hashlib.sha256(desc.encode("utf-8")).hexdigest()


def embed_all(
    nodes: list[dict],
    embed=None,
    cache_path: Path | None = None,
) -> dict[str, list[float] | None]:
    """Embed all node descriptions, using optional file cache keyed by node id + desc hash.

    Returns {node_id: vector or None} for each node. Nodes with None are excluded
    from comparison in find_similarity_gaps().
    """
    if embed is None:
        from lib.intent_classify import embed_text as embed

    cache_path = cache_path or HERE / "reports" / "embedding-cache.json"
    cache: dict[str, dict] = {}

    # Load existing cache if present
    if cache_path.exists():
        try:
            cache = json.loads(cache_path.read_text(encoding="utf-8"))
        except Exception:
            cache = {}

    vectors: dict[str, list[float] | None] = {}

    for node in nodes:
        node_id = node.get("id", "")
        desc = node.get("desc", "")
        desc_hash = _desc_hash(desc)

        # Check cache: if desc_hash matches, reuse cached vector
        cached = cache.get(node_id, {})
        if cached.get("desc_hash") == desc_hash and "vector" in cached:
            vectors[node_id] = cached["vector"]
            continue

        # Cache miss: embed the description
        vector = embed(desc, task="document")
        vectors[node_id] = vector

        # Update cache entry
        cache[node_id] = {
            "desc_hash": desc_hash,
            "vector": vector,
        }

    # Write cache atomically
    cache_path.parent.mkdir(parents=True, exist_ok=True)
    tmp_cache = cache_path.with_suffix(".tmp")
    tmp_cache.write_text(json.dumps(cache, indent=2, ensure_ascii=False), encoding="utf-8")
    tmp_cache.replace(cache_path)

    return vectors


def _get_cos():
    """Lazy import cosine similarity from board_registry."""
    try:
        # Try normal import first (works when run from repo root)
        from lib.board_registry import _cos  # noqa: F401
        return _cos
    except (ImportError, ModuleNotFoundError):
        # Fallback: implement locally to avoid import errors in test environments
        def _cos_impl(a: list[float], b: list[float]) -> float:
            na = math.sqrt(sum(x * x for x in a))
            nb = math.sqrt(sum(y * y for y in b))
            return sum(x * y for x, y in zip(a, b)) / (na * nb) if na and nb else 0.0
        return _cos_impl


def _get_has_direct_edge():
    """Lazy import synapse checker from shared_resource_pass."""
    try:
        # Try normal import first
        sys.path.insert(0, str(HERE))
        from shared_resource_pass import has_direct_edge  # noqa: F401
        sys.path.pop(0)
        return has_direct_edge
    except (ImportError, ModuleNotFoundError):
        # Fallback: implement locally
        def has_direct_edge_impl(node_a: str, node_b: str, synapses: list[dict]) -> bool:
            for synapse in synapses:
                a, b = synapse.get("a", ""), synapse.get("b", "")
                if (a == node_a and b == node_b) or (a == node_b and b == node_a):
                    return True
            return False
        return has_direct_edge_impl


def find_similarity_gaps(
    nodes: list[dict],
    vectors: dict[str, list[float] | None],
    synapses: list[dict],
    threshold: float = THRESHOLD,
) -> list[Finding]:
    """Find cross-category node pairs with high similarity but no direct edge."""
    # Lazy import dependencies
    _cos = _get_cos()
    has_direct_edge = _get_has_direct_edge()

    # Filter to nodes with valid embeddings
    embeddable = {n["id"]: n for n in nodes if vectors.get(n["id"]) is not None}

    if not embeddable:
        return []

    findings: list[Finding] = []

    # Iterate over all pairs of embeddable nodes
    for node_a_id, node_b_id in combinations(sorted(embeddable.keys()), 2):
        node_a = embeddable[node_a_id]
        node_b = embeddable[node_b_id]

        # Skip same-category pairs (scope: cross-category only, leave same-category to ticket #30)
        if node_a.get("cat") == node_b.get("cat"):
            continue

        # Skip pairs with existing synapses
        if has_direct_edge(node_a_id, node_b_id, synapses):
            continue

        # Compute similarity
        vec_a = vectors[node_a_id]
        vec_b = vectors[node_b_id]
        similarity = _cos(vec_a, vec_b) if vec_a and vec_b else 0.0

        # Keep pairs above threshold
        if similarity >= threshold:
            findings.append(
                Finding(
                    kind="embedding-similarity",
                    node_a=node_a_id,
                    node_b=node_b_id,
                    cat_a=node_a.get("cat", ""),
                    cat_b=node_b.get("cat", ""),
                    similarity=round(similarity, 4),
                    reason=f"semantically similar ({similarity:.2f}) across categories but have no synapse",
                )
            )

    return sorted(findings, key=lambda f: (f["node_a"], f["node_b"]))


def render_markdown(findings: list[Finding]) -> str:
    """Generate human-readable markdown report."""
    lines = [
        "# Embedding Similarity Gaps",
        "",
        f"Found {len(findings)} cross-category node pair(s) with high semantic similarity but no direct synapse.",
        "",
    ]

    if not findings:
        lines.append("No gaps detected.")
        return "\n".join(lines)

    # Group by category pair for readability
    by_cats: dict[tuple[str, str], list[Finding]] = {}
    for finding in findings:
        key = tuple(sorted([finding["cat_a"], finding["cat_b"]]))
        if key not in by_cats:
            by_cats[key] = []
        by_cats[key].append(finding)

    for (cat_a, cat_b), group in sorted(by_cats.items()):
        lines.append(f"## {cat_a} ↔ {cat_b}")
        lines.append("")
        for finding in sorted(group, key=lambda f: f["similarity"], reverse=True):
            lines.append(
                f"- **{finding['node_a']}** ↔ **{finding['node_b']}**: "
                f"{finding['similarity']:.3f} similarity\n  {finding['reason']}"
            )
        lines.append("")

    return "\n".join(lines)


def parse_args(args: list[str] | None = None) -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Find cross-category nodes with high semantic similarity."
    )
    parser.add_argument(
        "--threshold",
        type=float,
        default=THRESHOLD,
        help=f"Similarity threshold (0-1); default {THRESHOLD}",
    )
    parsed = parser.parse_args(args)

    # Validate threshold
    if not (0.0 <= parsed.threshold <= 1.0):
        parser.error(f"--threshold must be in range [0, 1], got {parsed.threshold}")

    return parsed


def write_json(data: list[Finding], path: Path) -> None:
    """Atomically write JSON findings to path."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(".tmp")
    tmp.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
    tmp.replace(path)


def write_md(text: str, path: Path) -> None:
    """Atomically write markdown report to path."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(path)


def main() -> None:
    args = parse_args()

    if not TREE_DATA_PATH.exists():
        print(
            f"ERROR: {TREE_DATA_PATH} not found. Run brain-map/generate.py first.",
            file=sys.stderr,
        )
        sys.exit(1)

    try:
        data = json.loads(TREE_DATA_PATH.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        print(
            f"ERROR: {TREE_DATA_PATH} is not valid JSON: {e}",
            file=sys.stderr,
        )
        sys.exit(1)

    tree, synapses = data.get("tree", {}), data.get("synapses", [])

    # Collect and embed nodes
    nodes = collect_nodes(tree)
    vectors = embed_all(nodes)

    # Count valid embeddings for state tracking
    valid_count = sum(1 for v in vectors.values() if v is not None)

    if not valid_count:
        # Total dependency outage: report inability to scan
        print(
            "ERROR: embedding backend unavailable — no nodes could be embedded. "
            "Cannot scan for similarity gaps.",
            file=sys.stderr,
        )
        sys.exit(1)

    # Find gaps
    findings = find_similarity_gaps(nodes, vectors, synapses, threshold=args.threshold)

    # Write outputs atomically
    try:
        write_json(findings, OUTPUT_JSON)
        md_content = render_markdown(findings)
        write_md(md_content, OUTPUT_MD)
    except PermissionError as e:
        print(f"ERROR: cannot write to {OUTPUT_DIR}: {e}", file=sys.stderr)
        sys.exit(1)

    print(f"Found {len(findings)} embedding-similarity gap(s) (threshold={args.threshold})")
    print(f"  JSON:  {OUTPUT_JSON}")
    print(f"  Markdown: {OUTPUT_MD}")


if __name__ == "__main__":
    main()
