#!/usr/bin/env python3
"""
shared_resource_pass.py — detect disconnected nodes that share a resource dependency.

Reads brain-map/tree-data.json (generated by generate.py) and identifies pairs of
nodes that both touch the same Memory resource (qa-knowledge, research-feed,
paper-knowledge, lexicon.md, manifest.json) but have no direct synapse edge
between them.

Reasoning: skills that both depend on the same resource often have implicit
coupling or shared context — missing direct edges may indicate opportunities
for explicit collaboration, or undeclared dependencies that should be surfaced.

Algorithm:
  1. Find Memory's direct children (the resource set)
  2. For each resource, collect all nodes touching it (synapse endpoints)
  3. For each pair of touchers, check for direct edge
  4. Emit findings for pairs with no edge, deduplicated by node pair across resources
  5. Tag findings with kind="shared-resource" and resource list for differentiation
     from sibling passes (#30 category-match, #31 embedding-similarity)

Output: brain-map/reports/shared-resource-gaps.json + .md rollup
"""
from __future__ import annotations
import json
import sys
from itertools import combinations
from pathlib import Path
from typing import TypedDict

HERE = Path(__file__).parent.parent
TREE_DATA_PATH = HERE / "tree-data.json"
OUTPUT_DIR = HERE / "reports"
OUTPUT_JSON = OUTPUT_DIR / "shared-resource-gaps.json"
OUTPUT_MD = OUTPUT_DIR / "shared-resource-gaps.md"


class Finding(TypedDict):
    kind: str
    resources: list[str]
    node_a: str
    node_b: str
    reason: str


def find_resources(tree: dict) -> set[str]:
    """Locate Memory node and return its direct children ids (resource set)."""
    def search(node: dict) -> set[str]:
        if node.get("id") == "Memory":
            return {c.get("id") for c in node.get("children", []) if c.get("id")}
        for child in node.get("children", []):
            result = search(child)
            if result:
                return result
        return set()

    return search(tree)


def touchers_by_resource(synapses: list[dict], resources: set[str]) -> dict[str, set[str]]:
    """For each resource, collect all distinct nodes touching it (either direction)."""
    touchers = {r: set() for r in resources}
    for synapse in synapses:
        a, b = synapse.get("a", ""), synapse.get("b", "")
        if a in resources:
            touchers[a].add(b)
        if b in resources:
            touchers[b].add(a)
    return touchers


def has_direct_edge(node_a: str, node_b: str, synapses: list[dict]) -> bool:
    """Check if any synapse connects node_a and node_b (either direction)."""
    for synapse in synapses:
        a, b = synapse.get("a", ""), synapse.get("b", "")
        if (a == node_a and b == node_b) or (a == node_b and b == node_a):
            return True
    return False


def find_gaps(tree: dict, synapses: list[dict]) -> list[Finding]:
    """Find pairs of touchers with no direct edge, deduplicated by node pair."""
    resources = find_resources(tree)
    if not resources:
        return []

    touchers = touchers_by_resource(synapses, resources)

    # Track all gaps by (node_a, node_b) unordered pair → list of resource ids
    gaps_by_pair: dict[tuple[str, str], list[str]] = {}

    for resource, resource_touchers in touchers.items():
        if len(resource_touchers) < 2:
            continue  # No pairs to check

        for node_a, node_b in combinations(sorted(resource_touchers), 2):
            if has_direct_edge(node_a, node_b, synapses):
                continue  # Skip pairs with direct edge
            # Normalize pair key (always smaller first) for dedup
            pair_key = tuple(sorted([node_a, node_b]))
            if pair_key not in gaps_by_pair:
                gaps_by_pair[pair_key] = []
            gaps_by_pair[pair_key].append(resource)

    # Convert to findings
    findings: list[Finding] = []
    for (node_a, node_b), resource_list in gaps_by_pair.items():
        findings.append(
            Finding(
                kind="shared-resource",
                resources=sorted(resource_list),
                node_a=node_a,
                node_b=node_b,
                reason=f"both touch {'/'.join(sorted(resource_list))} directly but have no synapse between each other",
            )
        )

    return sorted(findings, key=lambda f: (f["node_a"], f["node_b"]))


def render_markdown(findings: list[Finding]) -> str:
    """Generate human-readable markdown report."""
    lines = [
        "# Shared Resource Gaps",
        "",
        f"Found {len(findings)} node pair(s) sharing a resource but lacking direct synapse.",
        "",
    ]

    if not findings:
        lines.append("No gaps detected.")
        return "\n".join(lines)

    # Group by resources for readability
    by_resource: dict[str, list[Finding]] = {}
    for finding in findings:
        key = tuple(finding["resources"])
        if key not in by_resource:
            by_resource[key] = []
        by_resource[key].append(finding)

    for resources, group in sorted(by_resource.items()):
        lines.append(f"## {' + '.join(resources)}")
        lines.append("")
        for finding in sorted(group, key=lambda f: (f["node_a"], f["node_b"])):
            lines.append(
                f"- **{finding['node_a']}** ↔ **{finding['node_b']}**: "
                f"{finding['reason']}"
            )
        lines.append("")

    return "\n".join(lines)


def main() -> None:
    if not TREE_DATA_PATH.exists():
        print(
            f"ERROR: {TREE_DATA_PATH} not found. Run brain-map/generate.py first.",
            file=sys.stderr,
        )
        sys.exit(1)

    data = json.loads(TREE_DATA_PATH.read_text(encoding="utf-8"))
    tree, synapses = data["tree"], data["synapses"]

    findings = find_gaps(tree, synapses)

    # Ensure output directory exists
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # Write JSON
    OUTPUT_JSON.write_text(
        json.dumps(findings, indent=2, ensure_ascii=False), encoding="utf-8"
    )

    # Write markdown
    md_content = render_markdown(findings)
    OUTPUT_MD.write_text(md_content, encoding="utf-8")

    print(f"Found {len(findings)} shared-resource gap(s)")
    print(f"  JSON:  {OUTPUT_JSON}")
    print(f"  Markdown: {OUTPUT_MD}")


if __name__ == "__main__":
    main()
