"""Tests for ticket_agents.py. Run via:
    ~/.agents/venv/bin/python -m pytest lib/tests/test_ticket_agents.py -v
"""
from __future__ import annotations
import json
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

LIB = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(LIB))

import ticket_agents as ta  # noqa: E402

NOW = datetime(2026, 10, 5, 12, tzinfo=timezone.utc)
REPO = "G-Eskayo/marvin"


def iso(days_ago=0.0):
    return (NOW - timedelta(days=days_ago)).isoformat()


def issue(n, labels=(), body="", title="Ticket", created=1, updated=0.1):
    return {"number": n, "title": title, "labels": [{"name": l} for l in labels], "body": body,
            "createdAt": iso(created), "updatedAt": iso(updated)}


def ops(actions, **match):
    return [a for a in actions if all(a.get(k) == v for k, v in match.items())]


# ── modes ───────────────────────────────────────────────────────────────────

def test_auto_mode_proposes_until_the_date_then_acts():
    cfg = {"mode": "auto", "act_after": "2026-10-12", "agents": {}}
    assert ta.effective_mode(cfg, "prioritize", NOW) == "propose"
    assert ta.effective_mode(cfg, "prioritize", NOW + timedelta(days=8)) == "act"


def test_a_pinned_agent_never_flips_and_off_turns_everything_off():
    cfg = {"mode": "auto", "act_after": "2026-10-12", "agents": {"stale_claims": "propose", "triage": "off"}}
    later = NOW + timedelta(days=30)
    assert ta.effective_mode(cfg, "stale_claims", later) == "propose"
    assert ta.effective_mode(cfg, "triage", later) == "off"
    assert ta.effective_mode({"mode": "off"}, "prioritize", later) == "off"


def test_a_missing_or_corrupt_config_falls_back_to_propose_never_act(tmp_path):
    assert ta.load_config(tmp_path / "none.json")["mode"] == "propose"
    bad = tmp_path / "c.json"
    bad.write_text("{nope")
    assert ta.load_config(bad)["mode"] == "propose"


# ── prioritize ──────────────────────────────────────────────────────────────

def test_prioritize_labels_unlabelled_tickets_and_explains_why():
    issues = [issue(1), issue(2, body="## Blocked by\n\n- #1"), issue(3, body="Blocked by #1")]
    acts = ta.plan_prioritize(REPO, issues, due=None, owned={}, now=NOW)
    first = ops(acts, number=1, op="add_label")[0]
    assert first["arg"] in ("priority:p1", "priority:p2")  # #1 unblocks two tickets
    assert "unblocks 2" in first["why"]


def test_a_priority_someone_set_by_hand_is_left_alone():
    acts = ta.plan_prioritize(REPO, [issue(1, labels=["priority:p3"])], due=None, owned={}, now=NOW)
    assert acts == []


def test_a_priority_the_agent_set_earlier_is_updated_when_the_score_changes():
    t = issue(1, labels=["priority:p3", "bug"], created=45)
    acts = ta.plan_prioritize(REPO, [t], due={"date": "2026-10-07", "hard": True}, owned={1: "priority:p3"}, now=NOW)
    assert ops(acts, number=1, op="remove_label")[0]["arg"] == "priority:p3"
    assert ops(acts, number=1, op="add_label")[0]["arg"] == "priority:p0"


def test_prioritize_skips_pinned_tickets_and_tickets_already_at_the_right_priority():
    t_ok = issue(1)
    first = ta.plan_prioritize(REPO, [t_ok], None, {}, NOW)
    label = ops(first, op="add_label")[0]["arg"]
    again = ta.plan_prioritize(REPO, [issue(1, labels=[label])], None, {1: label}, NOW)
    assert again == []
    assert ta.plan_prioritize(REPO, [issue(2, labels=["pinned"])], None, {}, NOW) == []


# ── triage ──────────────────────────────────────────────────────────────────

GOOD = "## What to build\n\nA thing.\n\n## How we'll try to break it\n\nEmpty input.\n\n## Acceptance criteria\n\n- [ ] works\n"


def test_triage_marks_a_well_specified_ticket_ready_and_categorises_it():
    acts = ta.plan_triage(REPO, [issue(5, labels=["needs-triage"], body=GOOD, title="Add widget")])
    assert {a["arg"] for a in ops(acts, op="add_label")} == {"ready-for-agent", "enhancement"}
    assert ops(acts, op="remove_label")[0]["arg"] == "needs-triage"


def test_triage_asks_for_what_is_missing_with_the_ai_disclaimer():
    acts = ta.plan_triage(REPO, [issue(6, body="make it better")])
    c = ops(acts, op="comment")[0]
    assert c["arg"].startswith("> *This was generated by AI during triage.*")
    assert "acceptance criteria" in c["arg"]
    assert "needs-info" in {a["arg"] for a in ops(acts, op="add_label")}


def test_triage_leaves_already_triaged_tickets_alone():
    assert ta.plan_triage(REPO, [issue(7, labels=["ready-for-agent"], body=GOOD)]) == []


# ── stale claims ────────────────────────────────────────────────────────────

def test_a_stale_claim_with_no_work_in_flight_is_released_with_an_explanation():
    t = issue(10, labels=["claimed:mac-mini", "ready-for-agent"], updated=4)
    acts = ta.plan_stale_claims(REPO, [t], in_flight=set(), now=NOW)
    assert ops(acts, op="remove_label")[0]["arg"] == "claimed:mac-mini"
    assert "4 days" in ops(acts, op="comment")[0]["arg"] or "96" in ops(acts, op="comment")[0]["arg"]


def test_a_claim_is_never_released_while_there_is_work_in_flight_or_a_hold():
    stale = dict(updated=4)
    assert ta.plan_stale_claims(REPO, [issue(10, labels=["claimed:mac-mini"], **stale)], in_flight={10}, now=NOW) == []
    assert ta.plan_stale_claims(REPO, [issue(11, labels=["claimed:mac-mini", "held"], **stale)], in_flight=set(), now=NOW) == []
    assert ta.plan_stale_claims(REPO, [issue(12, labels=["claimed:mac-mini", "pinned"], **stale)], in_flight=set(), now=NOW) == []


# ── refeed ──────────────────────────────────────────────────────────────────

def test_a_denied_ticket_goes_back_to_the_queue_with_a_note():
    acts = ta.plan_refeed(REPO, [issue(20, labels=["needs-reengagement"])], counts={})
    assert ops(acts, op="remove_label")[0]["arg"] == "needs-reengagement"
    assert "ready-for-agent" in {a["arg"] for a in ops(acts, op="add_label")}
    assert "attempt 1 of 2" in ops(acts, op="comment")[0]["arg"]


def test_after_two_re_queues_it_goes_to_a_person_instead_of_looping():
    acts = ta.plan_refeed(REPO, [issue(20, labels=["needs-reengagement"])], counts={20: 2})
    assert "ready-for-human" in {a["arg"] for a in ops(acts, op="add_label")}
    assert "ready-for-agent" not in {a["arg"] for a in ops(acts, op="add_label")}


# ── running ─────────────────────────────────────────────────────────────────

class FakeGh:
    def __init__(self):
        self.calls = []

    def __call__(self, args):
        self.calls.append(args)
        return ""


def snapshot():
    return {REPO: {"issues": [issue(1), issue(2, labels=["needs-triage"], body=GOOD)], "prs": []}}


def run(tmp_path, cfg, gh=None, **kw):
    return ta.run(snapshot=snapshot(), gh=gh or FakeGh(), cfg=cfg, now=NOW, audit_path=tmp_path / "audit.jsonl",
                  proposals_path=tmp_path / "proposals.json", in_flight=lambda repo: set(), due_for=lambda repo: None, **kw)


def test_propose_mode_changes_nothing_but_records_every_proposal(tmp_path):
    gh = FakeGh()
    res = run(tmp_path, {"mode": "propose", "agents": {}}, gh)
    assert gh.calls == []
    assert res["applied"] == 0 and res["proposed"] > 0
    props = json.loads((tmp_path / "proposals.json").read_text())
    assert props["effective_mode"] == "propose" and props["proposals"]
    assert all(json.loads(l)["status"] == "proposed" for l in (tmp_path / "audit.jsonl").read_text().splitlines())


def test_act_mode_applies_changes_and_audits_them_with_what_was_there_before(tmp_path):
    gh = FakeGh()
    res = run(tmp_path, {"mode": "act", "agents": {}}, gh)
    assert res["applied"] > 0
    edits = [c for c in gh.calls if c[:2] == ["issue", "edit"]]
    assert edits and all("--repo" in c for c in edits)
    rows = [json.loads(l) for l in (tmp_path / "audit.jsonl").read_text().splitlines()]
    assert all(r["status"] == "applied" for r in rows) and all("before_labels" in r for r in rows)


def test_a_pinned_to_propose_agent_stays_proposal_only_even_when_the_rest_act(tmp_path):
    gh = FakeGh()
    snap = {REPO: {"issues": [issue(30, labels=["claimed:mac-mini"], updated=5)], "prs": []}}
    res = ta.run(snapshot=snap, gh=gh, cfg={"mode": "act", "agents": {"stale_claims": "propose"}}, now=NOW,
                 audit_path=tmp_path / "a.jsonl", proposals_path=tmp_path / "p.json", in_flight=lambda r: set(), due_for=lambda r: None)
    assert not any("claimed:mac-mini" in " ".join(c) for c in gh.calls)
    assert any(p["agent"] == "stale_claims" for p in json.loads((tmp_path / "p.json").read_text())["proposals"])
    assert res["by_agent"]["stale_claims"]["mode"] == "propose"


def test_a_failing_gh_call_is_recorded_and_does_not_stop_the_rest(tmp_path):
    n = {"i": 0}

    def flaky(args):
        n["i"] += 1
        if n["i"] == 1:
            raise RuntimeError("rate limited")
        return ""

    res = run(tmp_path, {"mode": "act", "agents": {}}, flaky)
    assert res["failed"] == 1 and res["applied"] > 0


def test_actions_per_run_are_capped_so_a_first_run_cannot_flood_github(tmp_path):
    big = {REPO: {"issues": [issue(i) for i in range(1, 80)], "prs": []}}
    gh = FakeGh()
    res = ta.run(snapshot=big, gh=gh, cfg={"mode": "act", "agents": {}}, now=NOW, audit_path=tmp_path / "a.jsonl",
                 proposals_path=tmp_path / "p.json", in_flight=lambda r: set(), due_for=lambda r: None)
    assert res["applied"] <= ta.MAX_ACTIONS_PER_RUN
    assert res["deferred"] > 0


def test_agent_owned_priorities_are_read_back_from_the_audit_log(tmp_path):
    a = tmp_path / "a.jsonl"
    a.write_text("\n".join(json.dumps(r) for r in [
        {"status": "applied", "agent": "prioritize", "repo": REPO, "number": 4, "op": "add_label", "arg": "priority:p1"},
        {"status": "proposed", "agent": "prioritize", "repo": REPO, "number": 5, "op": "add_label", "arg": "priority:p0"},
        {"status": "applied", "agent": "prioritize", "repo": REPO, "number": 4, "op": "remove_label", "arg": "priority:p1"},
        {"status": "applied", "agent": "prioritize", "repo": REPO, "number": 4, "op": "add_label", "arg": "priority:p2"},
    ]) + "\n")
    assert ta.owned_priorities(a, REPO) == {4: "priority:p2"}  # last applied wins; proposals do not count


def test_ready_work_in_projects_the_executor_cannot_run_is_counted_not_hidden():
    snap = {
        "G-Eskayo/marvin": {"issues": [issue(1, labels=["ready-for-agent"])], "prs": []},
        "G-Eskayo/clarity-captions": {"issues": [issue(1, labels=["ready-for-agent"]), issue(2, labels=["ready-for-agent", "claimed:x"]),
                                                  issue(3, labels=["ready-for-agent"], body="## Blocked by\n\n- #1")], "prs": []},
    }
    assert ta.ready_elsewhere(snap) == {"G-Eskayo/clarity-captions": 1}


def test_stale_claim_and_requeue_agents_cover_every_project_the_executor_can_run():
    cc = "G-Eskayo/clarity-captions"
    snap = {cc: {"issues": [issue(5, labels=["claimed:mac-mini"], updated=5), issue(6, labels=["needs-reengagement"])], "prs": []}}
    base = dict(snapshot=snap, gh=FakeGh(), cfg={"mode": "propose", "agents": {}}, now=NOW, in_flight=lambda r: set(), due_for=lambda r: None)
    import tempfile
    with tempfile.TemporaryDirectory() as d:
        paths = dict(audit_path=Path(d) / "a.jsonl", proposals_path=Path(d) / "p.json")
        without = ta.run(**base, **paths)
        with_exec = ta.run(**base, **paths, executable={"G-Eskayo/marvin", cc})
    assert without["by_agent"]["stale_claims"]["planned"] == 0  # the executor does not know this project yet
    assert with_exec["by_agent"]["stale_claims"]["planned"] > 0 and with_exec["by_agent"]["refeed"]["planned"] > 0


def test_ready_work_only_counts_as_waiting_when_the_executor_cannot_run_that_project():
    cc = "G-Eskayo/clarity-captions"
    snap = {cc: {"issues": [issue(1, labels=["ready-for-agent"])], "prs": []}}
    assert ta.ready_elsewhere(snap) == {cc: 1}
    assert ta.ready_elsewhere(snap, executable={"G-Eskayo/marvin", cc}) == {}


def test_adding_a_label_the_repo_has_never_had_creates_it_first():
    calls = []

    def gh(args):
        calls.append(args)
        if args[:2] == ["issue", "edit"] and not any(c[:2] == ["label", "create"] for c in calls):
            raise RuntimeError("'priority:p1' not found")
        return ""

    ta.apply_action({"op": "add_label", "repo": "G-Eskayo/clarity-captions", "number": 3, "arg": "priority:p1"}, gh)
    assert any(c[:3] == ["label", "create", "priority:p1"] for c in calls)
    assert [c[:2] for c in calls].count(["issue", "edit"]) == 2


def test_other_label_failures_are_not_swallowed():
    def gh(args):
        raise RuntimeError("HTTP 403 forbidden")

    try:
        ta.apply_action({"op": "add_label", "repo": "o/r", "number": 3, "arg": "bug"}, gh)
    except RuntimeError as e:
        assert "403" in str(e)
    else:
        raise AssertionError("must not hide a real failure")


def test_due_for_repo_carries_the_buckets_a_deadline_does_not_cover(tmp_path):
    import json
    p = tmp_path / "overrides.json"
    p.write_text(json.dumps({"clarity-captions": {"due": "2026-10-25", "dueHard": True, "dueExcludes": ["V", "x"]},
                             "plain": {"due": "2026-12-01"}}))
    assert ta.due_for_repo("G-Eskayo/clarity-captions", p) == {"date": "2026-10-25", "hard": True, "excludes": ["V", "X"]}
    assert ta.due_for_repo("G-Eskayo/plain", p) == {"date": "2026-12-01", "hard": False, "excludes": []}


# ── project_tag (ADR 0060, #298) ────────────────────────────────────────────

TAG_RULES = {"projects": {"marvin-mobile": {"repo": "G-Eskayo/marvin-mobile", "signals": ["MARVIN Mobile", "APNs"]},
                          "portfolio-website-updater": {"repo": "G-Eskayo/portfolio-website-updater", "signals": ["MARVIN page"]}}}


def test_project_tag_labels_clear_tickets_and_records_unclear_ones_for_health(tmp_path):
    snap = {REPO: {"issues": [issue(1, title="MARVIN Mobile: push key"), issue(2, title="APNs on the MARVIN page"),
                              issue(3, title="plain marvin work")], "prs": []}}
    gh = FakeGh()
    state = tmp_path / "tags.json"
    res = ta.run(snapshot=snap, gh=gh, cfg={"mode": "propose", "agents": {"project_tag": "act"}}, now=NOW,
                 audit_path=tmp_path / "a.jsonl", proposals_path=tmp_path / "p.json", in_flight=lambda r: set(),
                 due_for=lambda r: None, project_rules=TAG_RULES, tags_state_path=state)
    assert ["issue", "edit", "1", "--repo", REPO, "--add-label", "project:marvin-mobile"] in gh.calls
    assert res["by_agent"]["project_tag"] == {"mode": "act", "planned": 1}
    d = json.loads(state.read_text())
    assert [u["number"] for u in d["unclear"]] == [2] and d["pending"] == 0


def test_project_tag_in_propose_mode_counts_the_clear_ones_as_pending(tmp_path):
    snap = {REPO: {"issues": [issue(1, title="MARVIN Mobile: push key")], "prs": []}}
    state = tmp_path / "tags.json"
    ta.run(snapshot=snap, gh=FakeGh(), cfg={"mode": "propose", "agents": {}}, now=NOW, audit_path=tmp_path / "a.jsonl",
           proposals_path=tmp_path / "p.json", in_flight=lambda r: set(), due_for=lambda r: None,
           project_rules=TAG_RULES, tags_state_path=state)
    assert json.loads(state.read_text())["pending"] == 1


def test_project_tag_never_puts_back_a_label_a_person_removed(tmp_path):
    audit = tmp_path / "a.jsonl"
    audit.write_text(json.dumps({"status": "applied", "agent": "project_tag", "repo": REPO, "number": 1,
                                 "op": "add_label", "arg": "project:marvin-mobile"}) + "\n")
    snap = {REPO: {"issues": [issue(1, title="MARVIN Mobile: push key")], "prs": []}}
    gh = FakeGh()
    ta.run(snapshot=snap, gh=gh, cfg={"mode": "act", "agents": {}}, now=NOW, audit_path=audit,
           proposals_path=tmp_path / "p.json", in_flight=lambda r: set(), due_for=lambda r: None, project_rules=TAG_RULES)
    assert not any("project:marvin-mobile" in c for c in gh.calls)


def test_a_missing_label_is_created_when_gh_reports_it_on_stderr_as_the_real_gh_does():
    """2026-10-09: 133 priority labels failed: the real gh raises CalledProcessError whose message has no stderr, so
    the 'label not found -> create it' fallback never ran (the old test raised an Exception with the text in it)."""
    import subprocess
    calls = []

    def gh(args):
        calls.append(args)
        if args[:2] == ["issue", "edit"] and len([c for c in calls if c[:2] == ["issue", "edit"]]) == 1:
            raise subprocess.CalledProcessError(1, ["gh", *args], output="", stderr="failed to update: 'priority:p3' not found")
        return ""

    ta.apply_action({"repo": REPO, "number": 5, "op": "add_label", "arg": "priority:p3"}, gh)
    assert ["label", "create", "priority:p3", "--repo", REPO] in calls
    assert sum(1 for c in calls if c[:2] == ["issue", "edit"]) == 2


def test_triage_looks_again_at_needs_info_it_set_once_the_ticket_is_complete(tmp_path):
    """The documented loop 'you answer -> triaged again' never ran: needs-info was a final state."""
    good = "## Solution\n\ndo y\n\n## Acceptance\n\n- [ ] it works\n\n## How we'll try to break it\n\nbad input\n"
    audit = tmp_path / "a.jsonl"
    audit.write_text(json.dumps({"status": "applied", "agent": "triage", "repo": REPO, "number": 7, "op": "add_label", "arg": "needs-info"}) + "\n")
    issues = [issue(7, labels=["needs-info"], body=good), issue(8, labels=["needs-info"], body=good)]  # 8: a person set it
    acts = ta.plan_triage(REPO, issues, owned_needs_info=ta.owned_needs_info(audit, REPO))
    assert ops(acts, number=7, op="remove_label") and ops(acts, number=7, op="add_label", arg="ready-for-agent")
    assert not ops(acts, number=8)
    assert not ops(acts, number=7, op="comment")


# ── revisit (holds, #213) ───────────────────────────────────────────────────

def comment(body):
    return {"body": body, "createdAt": iso()}


def test_revisit_past_due_date_removes_hold_and_adds_needs_triage():
    import ticket_policy as pol
    past_comment = comment("Revisit by: 2026-10-01 — when Terry's review is done")
    issues = [issue(1, labels=["hold"], body="Working on it\n" + past_comment["body"])]
    comments_by_number = {1: [past_comment]}
    acts = ta.plan_revisit(REPO, issues, comments_by_number, {1, 2, 3}, NOW)
    remove_hold = ops(acts, number=1, op="remove_label", arg="hold")
    add_triage = ops(acts, number=1, op="add_label", arg="needs-triage")
    assert remove_hold and add_triage
    assert any("2026-10-01" in str(a) for a in acts)


def test_revisit_with_ref_to_closed_ticket_is_due_regardless_of_date():
    past_comment = comment("Revisit by: 2026-12-01 — when #42 is done")
    issues = [issue(1, labels=["hold"], body="Test")]
    comments_by_number = {1: [past_comment]}
    acts = ta.plan_revisit(REPO, issues, comments_by_number, {1, 2, 3}, NOW)  # #42 not in open_numbers
    assert ops(acts, number=1, op="remove_label", arg="hold")


def test_revisit_with_ref_to_open_ticket_is_not_due():
    comment_text = comment("Revisit by: 2026-12-01 — when #42 ships")
    issues = [issue(1, labels=["hold"], body="Test")]
    comments_by_number = {1: [comment_text]}
    acts = ta.plan_revisit(REPO, issues, comments_by_number, {42, 1, 2}, NOW)  # #42 is open
    assert not ops(acts, number=1, op="remove_label", arg="hold")


def test_hold_with_no_revisit_line_is_not_actioned():
    issues = [issue(1, labels=["hold"], body="No revisit line")]
    acts = ta.plan_revisit(REPO, issues, {}, {1, 2, 3}, NOW)
    assert acts == []


def test_pinned_hold_is_never_touched():
    comment_text = comment("Revisit by: 2026-10-01")
    issues = [issue(1, labels=["hold", "pinned"], body="Test")]
    comments_by_number = {1: [comment_text]}
    acts = ta.plan_revisit(REPO, issues, comments_by_number, {1, 2, 3}, NOW)
    assert acts == []


def test_two_due_holds_both_act_with_own_comments():
    c1 = comment("Revisit by: 2026-10-01 — reason A")
    c2 = comment("Revisit by: 2026-10-01 — reason B")
    issues = [
        issue(1, labels=["hold"], body="Test"),
        issue(2, labels=["hold"], body="Test"),
    ]
    comments_by_number = {1: [c1], 2: [c2]}
    acts = ta.plan_revisit(REPO, issues, comments_by_number, {1, 2, 3}, NOW)
    assert len(ops(acts, number=1, op="remove_label", arg="hold")) == 1
    assert len(ops(acts, number=2, op="remove_label", arg="hold")) == 1
    assert len(ops(acts, number=1, op="comment")) == 1
    assert len(ops(acts, number=2, op="comment")) == 1
    assert ops(acts, number=1, op="comment")[0]["arg"] != ops(acts, number=2, op="comment")[0]["arg"]


def test_revisit_produces_agent_comment_with_reason():
    comment_text = comment("Revisit by: 2026-10-01 — after design")
    issues = [issue(1, labels=["hold"], body="Waiting")]
    comments_by_number = {1: [comment_text]}
    acts = ta.plan_revisit(REPO, issues, comments_by_number, {1, 2, 3}, NOW)
    comment_act = ops(acts, number=1, op="comment")[0]
    assert comment_act["arg"].startswith(ta.AGENT_COMMENT_PREFIX)
    assert "2026-10-01" in comment_act["arg"]


def test_revisit_applies_correctly_with_multiple_repos():
    comment_text = comment("Revisit by: 2026-10-01")
    repo2 = "G-Eskayo/portfolio-website-updater"
    issues = [
        (REPO, [issue(1, labels=["hold"], body="Test")]),
        (repo2, [issue(2, labels=["hold"], body="Test")]),
    ]
    comments_map = {REPO: {1: [comment_text]}, repo2: {2: [comment_text]}}
    all_acts = []
    for repo, repo_issues in issues:
        acts = ta.plan_revisit(repo, repo_issues, comments_map.get(repo, {}), {1, 2}, NOW)
        all_acts.extend(acts)
    assert len(all_acts) >= 2
