"""Tests for ticket_agents.py. Run via:
    ~/.agents/venv/bin/python -m pytest lib/tests/test_ticket_agents.py -v
"""
from __future__ import annotations
import json
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

LIB = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(LIB))

import ticket_agents as ta  # noqa: E402

NOW = datetime(2026, 10, 5, 12, tzinfo=timezone.utc)
REPO = "G-Eskayo/marvin"


def iso(days_ago=0.0):
    return (NOW - timedelta(days=days_ago)).isoformat()


def issue(n, labels=(), body="", title="Ticket", created=1, updated=0.1):
    return {"number": n, "title": title, "labels": [{"name": l} for l in labels], "body": body,
            "createdAt": iso(created), "updatedAt": iso(updated)}


def ops(actions, **match):
    return [a for a in actions if all(a.get(k) == v for k, v in match.items())]


# ── modes ───────────────────────────────────────────────────────────────────

def test_auto_mode_proposes_until_the_date_then_acts():
    cfg = {"mode": "auto", "act_after": "2026-10-12", "agents": {}}
    assert ta.effective_mode(cfg, "prioritize", NOW) == "propose"
    assert ta.effective_mode(cfg, "prioritize", NOW + timedelta(days=8)) == "act"


def test_a_pinned_agent_never_flips_and_off_turns_everything_off():
    cfg = {"mode": "auto", "act_after": "2026-10-12", "agents": {"stale_claims": "propose", "triage": "off"}}
    later = NOW + timedelta(days=30)
    assert ta.effective_mode(cfg, "stale_claims", later) == "propose"
    assert ta.effective_mode(cfg, "triage", later) == "off"
    assert ta.effective_mode({"mode": "off"}, "prioritize", later) == "off"


def test_a_missing_or_corrupt_config_falls_back_to_propose_never_act(tmp_path):
    assert ta.load_config(tmp_path / "none.json")["mode"] == "propose"
    bad = tmp_path / "c.json"
    bad.write_text("{nope")
    assert ta.load_config(bad)["mode"] == "propose"


# ── prioritize ──────────────────────────────────────────────────────────────

def test_prioritize_labels_unlabelled_tickets_and_explains_why():
    issues = [issue(1), issue(2, body="## Blocked by\n\n- #1"), issue(3, body="Blocked by #1")]
    acts = ta.plan_prioritize(REPO, issues, due=None, owned={}, now=NOW)
    first = ops(acts, number=1, op="add_label")[0]
    assert first["arg"] in ("priority:p1", "priority:p2")  # #1 unblocks two tickets
    assert "unblocks 2" in first["why"]


def test_a_priority_someone_set_by_hand_is_left_alone():
    acts = ta.plan_prioritize(REPO, [issue(1, labels=["priority:p3"])], due=None, owned={}, now=NOW)
    assert acts == []


def test_a_priority_the_agent_set_earlier_is_updated_when_the_score_changes():
    t = issue(1, labels=["priority:p3", "bug"], created=45)
    acts = ta.plan_prioritize(REPO, [t], due={"date": "2026-10-07", "hard": True}, owned={1: "priority:p3"}, now=NOW)
    assert ops(acts, number=1, op="remove_label")[0]["arg"] == "priority:p3"
    assert ops(acts, number=1, op="add_label")[0]["arg"] == "priority:p0"


def test_prioritize_skips_pinned_tickets_and_tickets_already_at_the_right_priority():
    t_ok = issue(1)
    first = ta.plan_prioritize(REPO, [t_ok], None, {}, NOW)
    label = ops(first, op="add_label")[0]["arg"]
    again = ta.plan_prioritize(REPO, [issue(1, labels=[label])], None, {1: label}, NOW)
    assert again == []
    assert ta.plan_prioritize(REPO, [issue(2, labels=["pinned"])], None, {}, NOW) == []


# ── triage ──────────────────────────────────────────────────────────────────

GOOD = "## What to build\n\nA thing.\n\n## Acceptance criteria\n\n- [ ] works\n"


def test_triage_marks_a_well_specified_ticket_ready_and_categorises_it():
    acts = ta.plan_triage(REPO, [issue(5, labels=["needs-triage"], body=GOOD, title="Add widget")])
    assert {a["arg"] for a in ops(acts, op="add_label")} == {"ready-for-agent", "enhancement"}
    assert ops(acts, op="remove_label")[0]["arg"] == "needs-triage"


def test_triage_asks_for_what_is_missing_with_the_ai_disclaimer():
    acts = ta.plan_triage(REPO, [issue(6, body="make it better")])
    c = ops(acts, op="comment")[0]
    assert c["arg"].startswith("> *This was generated by AI during triage.*")
    assert "acceptance criteria" in c["arg"]
    assert "needs-info" in {a["arg"] for a in ops(acts, op="add_label")}


def test_triage_leaves_already_triaged_tickets_alone():
    assert ta.plan_triage(REPO, [issue(7, labels=["ready-for-agent"], body=GOOD)]) == []


# ── stale claims ────────────────────────────────────────────────────────────

def test_a_stale_claim_with_no_work_in_flight_is_released_with_an_explanation():
    t = issue(10, labels=["claimed:mac-mini", "ready-for-agent"], updated=4)
    acts = ta.plan_stale_claims(REPO, [t], in_flight=set(), now=NOW)
    assert ops(acts, op="remove_label")[0]["arg"] == "claimed:mac-mini"
    assert "4 days" in ops(acts, op="comment")[0]["arg"] or "96" in ops(acts, op="comment")[0]["arg"]


def test_a_claim_is_never_released_while_there_is_work_in_flight_or_a_hold():
    stale = dict(updated=4)
    assert ta.plan_stale_claims(REPO, [issue(10, labels=["claimed:mac-mini"], **stale)], in_flight={10}, now=NOW) == []
    assert ta.plan_stale_claims(REPO, [issue(11, labels=["claimed:mac-mini", "held"], **stale)], in_flight=set(), now=NOW) == []
    assert ta.plan_stale_claims(REPO, [issue(12, labels=["claimed:mac-mini", "pinned"], **stale)], in_flight=set(), now=NOW) == []


# ── refeed ──────────────────────────────────────────────────────────────────

def test_a_denied_ticket_goes_back_to_the_queue_with_a_note():
    acts = ta.plan_refeed(REPO, [issue(20, labels=["needs-reengagement"])], counts={})
    assert ops(acts, op="remove_label")[0]["arg"] == "needs-reengagement"
    assert "ready-for-agent" in {a["arg"] for a in ops(acts, op="add_label")}
    assert "attempt 1 of 2" in ops(acts, op="comment")[0]["arg"]


def test_after_two_re_queues_it_goes_to_a_person_instead_of_looping():
    acts = ta.plan_refeed(REPO, [issue(20, labels=["needs-reengagement"])], counts={20: 2})
    assert "ready-for-human" in {a["arg"] for a in ops(acts, op="add_label")}
    assert "ready-for-agent" not in {a["arg"] for a in ops(acts, op="add_label")}


# ── running ─────────────────────────────────────────────────────────────────

class FakeGh:
    def __init__(self):
        self.calls = []

    def __call__(self, args):
        self.calls.append(args)
        return ""


def snapshot():
    return {REPO: {"issues": [issue(1), issue(2, labels=["needs-triage"], body=GOOD)], "prs": []}}


def run(tmp_path, cfg, gh=None, **kw):
    return ta.run(snapshot=snapshot(), gh=gh or FakeGh(), cfg=cfg, now=NOW, audit_path=tmp_path / "audit.jsonl",
                  proposals_path=tmp_path / "proposals.json", in_flight=lambda repo: set(), due_for=lambda repo: None, **kw)


def test_propose_mode_changes_nothing_but_records_every_proposal(tmp_path):
    gh = FakeGh()
    res = run(tmp_path, {"mode": "propose", "agents": {}}, gh)
    assert gh.calls == []
    assert res["applied"] == 0 and res["proposed"] > 0
    props = json.loads((tmp_path / "proposals.json").read_text())
    assert props["effective_mode"] == "propose" and props["proposals"]
    assert all(json.loads(l)["status"] == "proposed" for l in (tmp_path / "audit.jsonl").read_text().splitlines())


def test_act_mode_applies_changes_and_audits_them_with_what_was_there_before(tmp_path):
    gh = FakeGh()
    res = run(tmp_path, {"mode": "act", "agents": {}}, gh)
    assert res["applied"] > 0
    edits = [c for c in gh.calls if c[:2] == ["issue", "edit"]]
    assert edits and all("--repo" in c for c in edits)
    rows = [json.loads(l) for l in (tmp_path / "audit.jsonl").read_text().splitlines()]
    assert all(r["status"] == "applied" for r in rows) and all("before_labels" in r for r in rows)


def test_a_pinned_to_propose_agent_stays_proposal_only_even_when_the_rest_act(tmp_path):
    gh = FakeGh()
    snap = {REPO: {"issues": [issue(30, labels=["claimed:mac-mini"], updated=5)], "prs": []}}
    res = ta.run(snapshot=snap, gh=gh, cfg={"mode": "act", "agents": {"stale_claims": "propose"}}, now=NOW,
                 audit_path=tmp_path / "a.jsonl", proposals_path=tmp_path / "p.json", in_flight=lambda r: set(), due_for=lambda r: None)
    assert not any("claimed:mac-mini" in " ".join(c) for c in gh.calls)
    assert any(p["agent"] == "stale_claims" for p in json.loads((tmp_path / "p.json").read_text())["proposals"])
    assert res["by_agent"]["stale_claims"]["mode"] == "propose"


def test_a_failing_gh_call_is_recorded_and_does_not_stop_the_rest(tmp_path):
    n = {"i": 0}

    def flaky(args):
        n["i"] += 1
        if n["i"] == 1:
            raise RuntimeError("rate limited")
        return ""

    res = run(tmp_path, {"mode": "act", "agents": {}}, flaky)
    assert res["failed"] == 1 and res["applied"] > 0


def test_actions_per_run_are_capped_so_a_first_run_cannot_flood_github(tmp_path):
    big = {REPO: {"issues": [issue(i) for i in range(1, 80)], "prs": []}}
    gh = FakeGh()
    res = ta.run(snapshot=big, gh=gh, cfg={"mode": "act", "agents": {}}, now=NOW, audit_path=tmp_path / "a.jsonl",
                 proposals_path=tmp_path / "p.json", in_flight=lambda r: set(), due_for=lambda r: None)
    assert res["applied"] <= ta.MAX_ACTIONS_PER_RUN
    assert res["deferred"] > 0


def test_agent_owned_priorities_are_read_back_from_the_audit_log(tmp_path):
    a = tmp_path / "a.jsonl"
    a.write_text("\n".join(json.dumps(r) for r in [
        {"status": "applied", "agent": "prioritize", "repo": REPO, "number": 4, "op": "add_label", "arg": "priority:p1"},
        {"status": "proposed", "agent": "prioritize", "repo": REPO, "number": 5, "op": "add_label", "arg": "priority:p0"},
        {"status": "applied", "agent": "prioritize", "repo": REPO, "number": 4, "op": "remove_label", "arg": "priority:p1"},
        {"status": "applied", "agent": "prioritize", "repo": REPO, "number": 4, "op": "add_label", "arg": "priority:p2"},
    ]) + "\n")
    assert ta.owned_priorities(a, REPO) == {4: "priority:p2"}  # last applied wins; proposals do not count


def test_ready_work_in_projects_the_executor_cannot_run_is_counted_not_hidden():
    snap = {
        "G-Eskayo/marvin": {"issues": [issue(1, labels=["ready-for-agent"])], "prs": []},
        "G-Eskayo/clarity-captions": {"issues": [issue(1, labels=["ready-for-agent"]), issue(2, labels=["ready-for-agent", "claimed:x"]),
                                                  issue(3, labels=["ready-for-agent"], body="## Blocked by\n\n- #1")], "prs": []},
    }
    assert ta.ready_elsewhere(snap) == {"G-Eskayo/clarity-captions": 1}


def test_stale_claim_and_requeue_agents_cover_every_project_the_executor_can_run():
    cc = "G-Eskayo/clarity-captions"
    snap = {cc: {"issues": [issue(5, labels=["claimed:mac-mini"], updated=5), issue(6, labels=["needs-reengagement"])], "prs": []}}
    base = dict(snapshot=snap, gh=FakeGh(), cfg={"mode": "propose", "agents": {}}, now=NOW, in_flight=lambda r: set(), due_for=lambda r: None)
    import tempfile
    with tempfile.TemporaryDirectory() as d:
        paths = dict(audit_path=Path(d) / "a.jsonl", proposals_path=Path(d) / "p.json")
        without = ta.run(**base, **paths)
        with_exec = ta.run(**base, **paths, executable={"G-Eskayo/marvin", cc})
    assert without["by_agent"]["stale_claims"]["planned"] == 0  # the executor does not know this project yet
    assert with_exec["by_agent"]["stale_claims"]["planned"] > 0 and with_exec["by_agent"]["refeed"]["planned"] > 0


def test_ready_work_only_counts_as_waiting_when_the_executor_cannot_run_that_project():
    cc = "G-Eskayo/clarity-captions"
    snap = {cc: {"issues": [issue(1, labels=["ready-for-agent"])], "prs": []}}
    assert ta.ready_elsewhere(snap) == {cc: 1}
    assert ta.ready_elsewhere(snap, executable={"G-Eskayo/marvin", cc}) == {}


def test_adding_a_label_the_repo_has_never_had_creates_it_first():
    calls = []

    def gh(args):
        calls.append(args)
        if args[:2] == ["issue", "edit"] and not any(c[:2] == ["label", "create"] for c in calls):
            raise RuntimeError("'priority:p1' not found")
        return ""

    ta.apply_action({"op": "add_label", "repo": "G-Eskayo/clarity-captions", "number": 3, "arg": "priority:p1"}, gh)
    assert any(c[:3] == ["label", "create", "priority:p1"] for c in calls)
    assert [c[:2] for c in calls].count(["issue", "edit"]) == 2


def test_other_label_failures_are_not_swallowed():
    def gh(args):
        raise RuntimeError("HTTP 403 forbidden")

    try:
        ta.apply_action({"op": "add_label", "repo": "o/r", "number": 3, "arg": "bug"}, gh)
    except RuntimeError as e:
        assert "403" in str(e)
    else:
        raise AssertionError("must not hide a real failure")


def test_due_for_repo_carries_the_buckets_a_deadline_does_not_cover(tmp_path):
    import json
    p = tmp_path / "overrides.json"
    p.write_text(json.dumps({"clarity-captions": {"due": "2026-10-25", "dueHard": True, "dueExcludes": ["V", "x"]},
                             "plain": {"due": "2026-12-01"}}))
    assert ta.due_for_repo("G-Eskayo/clarity-captions", p) == {"date": "2026-10-25", "hard": True, "excludes": ["V", "X"]}
    assert ta.due_for_repo("G-Eskayo/plain", p) == {"date": "2026-12-01", "hard": False, "excludes": []}
